

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: ${{ matrix.os }}

    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 21.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run install in preparation for node app
      run: npm install
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: node-app-artifact-${{ matrix.node-version }}-${{ matrix.os }}
        path: .
  
  Tests: 

    runs-on: ${{ matrix.os }}
    needs: [Build]
    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 21.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: node-app-artifact-${{ matrix.node-version }}-${{ matrix.os }}
          path: .
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests for node app
        run: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-app-artifact-${{ matrix.node-version }}-${{ matrix.os }}-tests
          path: .

    

