

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: ${{ matrix.os }}

    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 21.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run install in preparation for node app
      run: npm install

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: node-modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node-modules-${{ matrix.os }}-${{ matrix.node-version }}-
          node-modules-${{ matrix.os }}-
  
  Tests: 

    runs-on: ${{ matrix.os }}
    needs: [Build]
    env:
      CI: true

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x, 21.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-${{ matrix.os }}-${{ matrix.node-version }}-
            node-modules-${{ matrix.os }}-

      - name: Run tests for node app
        run: npm test
    

